[project]
name = "TrendLink"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.trend-market]
path = "contracts/trend-market.clar"
depends_on = []

[contracts.trend-token]
path = "contracts/trend-token.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
